version: '2'

services:
  pool:
    image: pexa/pool:latest
    build:
      context: .
    ports:
      - 3333:3333
    expose:
      - 3333
    environment:
      - VIRTUAL_HOST=pool.pexa.dev
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pool.pexa.dev
      - LETSENCRYPT_EMAIL=dev@pexaproject.com
    volumes:
      - /data:/var/opt

  redis:
    image: redis:5.0.5-alpine
    ports:
      - '6379:6379'

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:
  dhparam: